name: On-Chain Search CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Python 3.11
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest matplotlib

      # 4. Lint code (ignore minor style issues)
      - name: Lint source code
        run: |
          flake8 src --count --statistics \
            --max-line-length=100 \
            --ignore=E203,E226,E228,E231,E302,E401,E402,E501,F401,F841,W291

      # 5. Set PYTHONPATH so tests can import src modules
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV

      # 6. Run unit tests
      - name: Run unit tests
        run: pytest tests/ --maxfail=1 --disable-warnings -v

      # 7. Prepare output directories for demo
      - name: Create output directories
        run: mkdir -p charts outputs

      # 8. Run demo script
      - name: Run demo
        run: bash ./run_demo.sh || true

      # 9. Upload charts as artifacts
      - name: Upload charts
        uses: actions/upload-artifact@v4
        with:
          name: charts
          path: charts/

      # 10. Upload outputs as artifacts
      - name: Upload outputs
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: outputs/
