name: On-Chain Boolean Prototype CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest matplotlib black isort

      # Set PYTHONPATH for tests
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV

      # Lint the source code (report only, don’t fail build)
      - name: Lint source code (non-strict)
        run: |
          flake8 src --count --statistics \
            --max-line-length=100 \
            --ignore=E203,E226,E228,E231,E302,E401,E402,E501,F401,F841,W291,W292 || true

      # Auto-format with black and isort (optional)
      - name: Format code (optional)
        run: |
          black --check src tests || true
          isort --check-only src tests || true

      # Run unit tests
      - name: Run tests
        run: pytest -q --maxfail=1 --disable-warnings -v

      # Run demo script
      - name: Run demo
        run: bash run_demo.sh

      # Upload outputs
      - name: Upload outputs
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: outputs/

      # Upload charts
      - name: Upload charts
        uses: actions/upload-artifact@v4
        with:
          name: charts
          path: charts/
